name: Linear Issue Reminder

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  check-linear-issues:
    runs-on: ubuntu-latest
    # Only run on non-draft PRs
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Wait for 30 seconds to allow linear bot to reply
        run: sleep 30
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install @actions/github @actions/core
        
      - name: Check for Linear issue links
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, 'scripts', 'check-linear-issues.js');
            const script = require(scriptPath);
            if (!fs.existsSync(scriptPath)) {
              console.error(`Script not found at ${scriptPath}`);
              process.exit(1);
            }
            await script({github, context})
